master:
  prefix: catb
  release_mode: patch
  description: This is model description
  train_key: train
  dev_key: dev
  test_key: test
  save_path: 'D:\WorkBench\TA NLP\res'
  label_key: Label
  labels: Uncorrelated_Contra Sarcasm_Pro_Neutral_Contra_Pro Sarcasm
loader:
  data_path: 'D:\WorkBench\TA NLP\dataset_splitted\rey_rus'
  test_data_path: 'D:\WorkBench\TA NLP\dataset_splitted\test.csv'
  type: shallow
  model_type: catb
  key_list: Tweet_Comment
embedder:
  model_type: word2vec
  model_behavior: concat
  is_pretrained: true
  retrain: true
  model_path: 'D:\WorkBench\TA NLP\pretrained_models\w2v\word2vec.model'
  key_list: Tweet_Comment
  vector_size: 100
  window: 5
  min_count: 1
  epoch: 5
  max_sequence: 101
  log_oov: false
classifier:
  load_model: false
  model_path: tst
  type: catb
  config:
    loss_function: "MultiClass"
    learning_rate: 0.35
    iterations: 2000
    eval_metric: "TotalF1"
    od_wait: 200
    od_type: "Iter"
  decomposer:
    load_model: false
    model_path: tst
    type: pca
    decomposer_config:
      n_components: 0.8
      svd_solver: auto
