master:
  prefix: bert | xlnet
  release_mode: patch
  description: This is model description
  train_key: train
  dev_key: dev
  save_path: D:\WorkBench\TA NLP\res
  sampling: false
  labels: 'Uncorrelated_Contra Sarcasm_Pro_Neutral_Contra_Pro Sarcasm'
  label_key: Label
  key_list: Tweet_Comment
loader:
  data_path: D:\WorkBench\TA NLP\dataset_splitted\rey_rus
  tokenizer_type: bert | xlnet
  model_name: indobenchmark/indobert-base-p2 | malay-huggingface/xlnet-tiny-bahasa-cased
  tokenizer_config:
    max_length: 280
    padding: max_length
    return_tensors: tf
    truncation: true
classifier:
  type: bert | xlnet
  model_name: indobenchmark/indobert-base-p2 | malay-huggingface/xlnet-tiny-bahasa-cased

