master:
  release_mode: patch
  prefix: svm
  save_path: D:\WorkBench\TA NLP\res
  label_key: Label
  sampling: false
  labels: 'Uncorrelated_Contra Sarcasm_Pro_Neutral_Contra_Pro Sarcasm'
train_key: "train"
test_key: "test"
loader:
  data_path: D:\WorkBench\TA NLP\dataset_splitted\rey_rus
  type: shallow
  model_type: svm
embedder:
  model_type: word2vec
  model_behavior: concat
  is_pretrained: true
  model_path: D:\WorkBench\TA NLP\pretrained_models\w2v\word2vec.model
  key_list: Tweet_Comment
  vector_size: 100
  window: 5
  min_count: 1
  epoch: 5
  max_sequence: 101
  log_oov: false
regressor:
  type: svc
  kernel: rbf
  gamma: scale
  verbose: true
  max_iter: -1
  degree: 3
  decomposer:
    variance_tolerance: 0.8
    svd_solver: auto

